### ISSUE TITLE
敢问楼主这是hexo博客框架的主题吗？

### ISSUE THREAD

**Issue by YGQ8988** [ourfor/ourfor.github.io#1]
楼主是否可以公开此主题呢？看着好酷炫，如果可以。能告知如何使用吗？谢谢

**Comment by ourfor** [comment]
- 这个是网站的静态页面，主题是hexo博客框架的主题
- 主题为[Mellow](https://github.com/codefine/hexo-theme-mellow)
- 主题的` WIKI `里面有详细的使用教程，如果有遇到没有提到的问题，可以加群讨论，群号见主题仓库*README*
